---
title: "cryptic bio main figures"
author: "MZ"
date: "2024-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
###load packages/libraries/scripts
library(tidyverse)
library(ggrepel)
library(patchwork)

source(here::here('trial_nmd_plots.R'))

#check you're in right folder
here::here()
```

### TDP-43 cryptic exon biology paper
## Figure 1 - sensitivity of CEs to TDP43 LoF is driven by their cis features 
```{r, echo = FALSE}
master_table <- read.csv(here::here("data/master_table.csv"))

#####
print("1A")
list_gene = c("STMN2", "UNC13A", "HDGFL2", "AARS1")
big_data_filtereds_early_late_sh <- master_table %>% #[,c(2,1,3:9,20:24)] %>%
    mutate(dox0 = dox0_sh) %>% 
    select(c(gene,paste_into_igv_junction,strand,junc_cat,cryptic,junction_for_clustering,
             dox0,dox0125,dox0187,dox021,dox025,dox075,
             tdp43_sensitivity_sh,max_psi_sh)) %>% 
    group_by(gene) %>% 
    arrange(desc(dox025)) %>% 
    distinct(gene, .keep_all = T) %>% 
    filter(cryptic == "yes" & #junction_for_clustering == "yes" & 
             !is.na(dox0)) %>%
  pivot_longer(cols = c(7:12)) %>% 
  mutate(name = factor(name, levels = c("dox0","dox0125", "dox0187", "dox021", "dox025", "dox075"))) %>%
  mutate(label_junction = case_when(name == "dox025" & gene %in% list_gene ~ gene, T ~ ""))
table(big_data_filtereds_early_late_sh$tdp43_sensitivity_sh)
table(big_data_filtereds_early_late_sh$max_psi_sh)

big_data_filtereds_early_late_sh %>%
  ggplot(mapping = aes(x = name, y = value, group = paste_into_igv_junction)) +
  geom_line(aes(color = tdp43_sensitivity_sh), show.legend = F) +
  geom_text_repel(aes(label = label_junction), point.padding = 0.3,
                  nudge_y = 0.2, min.segment.length = 0.5, box.padding  = 2, max.overlaps = Inf, size=4, show.legend = F) +
  #geom_hline(yintercept = 0.2, linetype = "dotted") +
  scale_color_manual(values = c("#E41A1C", "#377EB8", "#4DAF4A")) + #, "#984EA3", "#000000")) +
  #scale_alpha_manual(values = c(0.1,1)) +
  xlab("TDP-43 knockdown level") +
  ylab("PSI") +
  scale_x_discrete(labels = c("-", "+", "++", "+++", "++++", "+++++")) +
  scale_y_continuous(breaks=seq(0,1,0.2)) +
  facet_wrap(~tdp43_sensitivity_sh) + 
  theme_classic()

print("1B")
big_data_filtereds_early_late_be2 <- master_table %>% #[,c(2,1,3:9,20:24)] %>%
    mutate(dox0 = dox0_be2) %>% 
    select(c(gene,paste_into_igv_junction,strand,junc_cat,cryptic,junction_for_clustering,
             dox0,dox002,dox003,dox004,dox005,dox0075,dox01,dox1,
             #dox0,dox0125,dox0187,dox021,dox025,dox075,
             tdp43_sensitivity_be2,max_psi_be2)) %>% 
    group_by(gene) %>% 
    arrange(desc(dox01)) %>% 
    distinct(gene, .keep_all = T) %>% 
  filter(cryptic == "yes" & #junction_for_clustering == "yes" & 
             !is.na(dox0)) %>%
  pivot_longer(cols = c(7:14)) %>% 
  mutate(name = factor(name, levels = c("dox0","dox002","dox003","dox004","dox005","dox0075","dox01","dox1"))) %>%
  mutate(label_junction = case_when(name == "dox01" & gene %in% list_gene ~ gene, T ~ ""))
table(big_data_filtereds_early_late_be2$tdp43_sensitivity_be2)
table(big_data_filtereds_early_late_be2$max_psi_be2)

big_data_filtereds_early_late_be2 %>%
  ggplot(mapping = aes(x = name, y = value, group = paste_into_igv_junction)) +
  geom_line(aes(color = tdp43_sensitivity_be2), show.legend = F) +
  geom_text_repel(aes(label = label_junction), point.padding = 0.3,
                  nudge_y = 0.2, min.segment.length = 0.5, box.padding  = 2, max.overlaps = Inf, size=4, show.legend = F) +
  #geom_hline(yintercept = 0.2, linetype = "dotted") +
  scale_color_manual(values = c("#E41A1C", "#377EB8", "#4DAF4A")) + #, "#984EA3", "#000000")) +
  #scale_alpha_manual(values = c(0.1,1)) +
  xlab("TDP-43 knockdown level") +
  ylab("PSI") +
  scale_x_discrete(labels = c("-", "+", "++", "+++", "++++", "+++++", "++++++", "+++++++")) +
  scale_y_continuous(breaks=seq(0,1,0.2)) +
  facet_wrap(~tdp43_sensitivity_be2) + 
  theme_classic()

print("1C")
  
```
A. Spaghetti plot in SH-SY5Y
B. Spaghetti plot in BE(2)
C.
D.

## Figure 2 - NMD
```{r, echo=FALSE}
print("2A")

print("2B")
gene_list_slope <- c("STMN2", "UNC13A", "AARS1", "HDGFL2", "CYFIP2", "SYNE1")
input_list <- c("Control_Control",
                "Cycloheximide_Control", 
                "Control_TDP43KD", 
                "Cycloheximide_TDP43KD")
big_data_chx <- read.csv(here::here('data','nmd_or_not.csv'))
a <- slope_plot_nmd(big_data_chx, 
               gene_list_slope)

print("2C")

```
A. 
B.
C.
D.

## Figure 3 - compendium / in vivo
```{r, echo=FALSE}
##load targeted seq table and compute CE ratio / rename samples in agreement to UNC13A paper
maxc <- read.csv("~/Desktop/ce_bio/count_table_of_aligned_remove_200bp_plus_product_reads.csv") %>%
  mutate(fraction_cryptic = n_cryptic / n_counts_for_gene) %>%
  mutate(sample_name_ari = case_when(sample_name == "P64_11" ~ "HC1",
                                     sample_name == "P17_07" ~ "HC2",
                                     sample_name == "P47_11" ~ "HC3",
                                     sample_name == "P35_07" ~ "HC4",
                                     sample_name == "P56_13" ~ "FTD1",
                                     sample_name == "P45_15" ~ "FTD2",
                                     sample_name == "P63_05" ~ "FTD3",
                                     sample_name == "P28_07" ~ "FTD4",
                                     sample_name == "P40_04" ~ "FTD5",
                                     sample_name == "P07_15" ~ "FTD6",
                                     sample_name == "P16_09" ~ "FTD7",
                                     sample_name == "P86_08" ~ "FTD8",
                                     sample_name == "P13_13" ~ "FTD9",
                                     sample_name == "P11_07" ~ "FTE10",
                                     sample_name == "ddH2O" ~ "HO2O")) #%>%
  #pivot_wider(names_from = sample_name_ari, values_from = ratio_cryptic)
table(maxc$sample_name_ari)

maxc %>%
  #filter(gene_name == "UNC13A") %>% ###if to compare to unc13a paper
  pivot_longer(cols = c(n_counts_for_gene, n_cryptic)) %>%#+
  ggplot(aes(x = sample_name_ari, y = value, fill = name)) +  #, fill = gene_name)) +
  geom_col(position = position_dodge(width = 0.8)) +
  scale_color_manual(values = "black") +
  facet_wrap(~name, scale = 'free_y', ncol = 1) +
  theme_bw()

##use only TDP43path-specific genes (use list from AL) - this is exluding more than 2/3 of genes!!
al <- read.csv("~/Desktop/ce_bio/expression_by_pathology_updated.csv") %>%
  dplyr::filter(fraction_path > 0.01 & fraction_not_path < 0.005) %>% ####need to carefully check this with AL
  distinct(gene, .keep_all = T) ##check when binding with annotated validation table - should be ok since left_join
names(al)[4] <- "gene_name"
maxc_al <- maxc %>%
  left_join(al, by = "gene_name") %>%
  dplyr::filter(!is.na(paste_into_igv_junction))
table(maxc_al$sample_name_ari)
table(maxc_al$gene_name)

maxc_al %>%
  dplyr::filter(gene_name != "SETD5") %>%
  pivot_longer(cols = c(n_counts_for_gene, n_cryptic)) %>%#+
  #filter(gene_name != "SETD5") %>% #|
  #filter(gene_name == "UNC13A") %>% # |
  #         gene_name == "AARS") %>%
  ggplot(aes(x = sample_name_ari, y = value, fill = name)) +  #, fill = gene_name)) +
  geom_col(position = position_dodge(width = 0.8)) +
  scale_color_manual(values = "black") +
  facet_grid(facets = vars(name), scale = 'free_y') +
  theme_bw()



##check igv files for these genes
maxc_type <- maxc_al %>%
  select(-type) %>%
  mutate(gene = gene_name) %>%
  filter(gene_name != "SETD5") %>%
  left_join(master_table, by = "paste_into_igv_junction") %>%
  filter(!is.na(tdp43_sensitivity_sh)) %>% 
  mutate(group = ifelse(grepl("FT", sample_name_ari), "FTD",
                        ifelse(grepl("HC", sample_name_ari), "HC",
                               "H2O"))) %>% 
  group_by(gene_name) %>%
  filter(sum(n_cryptic) > 0) %>%
  ungroup() %>% 
    filter(group != "H2O")


maxc_type %>%
  filter(tdp43_sensitivity_sh != "") %>%
  filter(gene_name != "SETD5") %>%
  #filter(detected == "Yes") %>%
  filter(group != "H2O") %>%
  ggplot(aes(x = tdp43_sensitivity_sh)) +
  geom_bar(aes(fill = tdp43_sensitivity_sh)) +
  facet_wrap(facets = vars(group), ncol = 2) +
  scale_fill_brewer(palette = "Set1") +
  xlab("") +
  ylab("Count of cryptic exons detected by targeted panel") +
  labs(fill = "Category") +
  theme_bw()

maxc_earli <- maxc_type %>%
  filter(tdp43_sensitivity_sh == "Earli") %>%
  filter(gene_name != "SETD5") %>% 
  ggplot(aes(x = sample_name_ari, y = fraction_cryptic)) +
  geom_bar(aes(fill = gene_name), stat = "identity", position = "stack", color="black") + #position = position_dodge(width = 0.8)) +
  #facet_grid(facets = vars(gene_name)) +
  scale_fill_brewer(palette = "Reds") +
  scale_y_continuous(limits = c(0,0.3)) +
  labs(x = "", y = "", fill = "Earli") +
  #scale_fill_manual(values = randomcoloR::distinctColorPalette(k = 30)) +
  theme_bw()
maxc_early <- maxc_type %>%
  filter(tdp43_sensitivity_sh == "Early") %>%
  filter(gene_name != "SETD5") %>% 
  ggplot(aes(x = sample_name_ari, y = fraction_cryptic)) +
  geom_bar(aes(fill = gene_name), stat = "identity", position = "stack", color="black") +#position = position_dodge(width = 0.8)) +
  #facet_grid(facets = vars(gene_name)) +
  scale_fill_brewer(palette = "Reds") +
  scale_y_continuous(limits = c(0,0.3)) +
  labs(x = "", y = "", fill = "Early") +
  #scale_fill_manual(values = randomcoloR::distinctColorPalette(k = 30)) +
  theme_bw()
maxc_intermediate <- maxc_type %>%
  filter(tdp43_sensitivity_sh == "Intermediate") %>%
  filter(gene_name != "SETD5") %>%
  ggplot(aes(x = sample_name_ari, y = fraction_cryptic)) +
  geom_bar(aes(fill = gene_name), stat = "identity", position = "stack", color="black") +#position = position_dodge(width = 0.8)) +
  #facet_grid(facets = vars(gene_name)) +
  scale_fill_brewer(palette = "Greens") +
  scale_y_continuous(limits = c(0,0.3)) +
  labs(x = "", y = "", fill = "Intermediate") +
  #scale_fill_manual(values = randomcoloR::distinctColorPalette(k = 30)) +
  theme_bw()
maxc_late <- maxc_type %>%
  filter(tdp43_sensitivity_sh == "Late") %>%
  filter(gene_name != "SETD5") %>%
  ggplot(aes(x = sample_name_ari, y = fraction_cryptic)) +
  geom_bar(aes(fill = gene_name), stat = "identity", position = "stack", color="black") +#position = position_dodge(width = 0.8)) +
  #facet_grid(facets = vars(gene_name)) +
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = c(0,0.3)) +
  labs(x = "", y = "", fill = "Late") +
  #scale_fill_manual(values = randomcoloR::distinctColorPalette(k = 30)) +
  theme_bw()

#maxc_earli / 
    maxc_early / maxc_intermediate / maxc_late #/ maxc_na


maxc_type %>%
  filter(group != "H2O") %>%
    filter(tdp43_sensitivity_sh != "") %>% 
  ggplot(aes(x = sample_name_ari, y = gene_name, fill = fraction_cryptic)) +
  geom_tile() +
  #scale_fill_viridis_d() +
  scale_fill_gradient(low = "white", high = "black") +
  facet_grid(rows = vars(tdp43_sensitivity_sh), cols = vars(group), 
             scales = "free", space = "free") +
  ylab("") + xlab("Sample name") + labs(fill = "CE fraction") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))


```
A.
B.
C. Detection of CEs from in vivo samples
D.
